name: 📃 Docs
description: Таски по документированию
title: '[Docs]'
type: 'Docs'
projects: ['phoenix-games-revolution/5']
assignees: Gochicus
body:
  - type: input
    id: motivation
    attributes:
      label: Область документирования?
      placeholder: Например, экономика, военное дело, строительство, политика
    validations:
      required: false

  - type: textarea
    id: poc
    attributes:
      label: Опиши структуру документа, чтобы она была понятна всем
      placeholder: Здесь должен находится примерный план по созданию документа
    validations:
      required: true

  - type: input
    id: materials
    attributes:
      label: Источники
      placeholder: Ссылка на фигму, дискуссию, комменты, внешние источники
    validations:
      required: true